apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE}
  labels:
    app: ${SERVICE}
  annotations:
    monitoring: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${SERVICE}
  template:
    metadata:
      labels:
        app: ${SERVICE}
    spec:
      containers:
        - image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
          name: ${SERVICE}
          ports:
            - containerPort: 80
            - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${SERVICE}
  name: ${SERVICE}
spec:
  ports:
    - name: demo-multitech-vue
      nodePort: 30100
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: ${SERVICE}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${SERVICE}
  name: demo-multitech-metrics
spec:
  ports:
    - name: demo-multitech-metrics
      nodePort: 30101
      port: 9113
      protocol: TCP
      targetPort: 9113
  selector:
    app: ${SERVICE}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: demo-multitech-proxy
spec:
  ports:
    - name: pod-port
      protocol: "TCP"
      port: 9113
      targetPort: 9113
  selector:
    app: ${SERVICE}
