version: '3'

services:
  server:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    ports:
      - 8090:80
    deploy:
      replicas: 2
    networks:
      demo-multitech-network:
        aliases:
          - demo-multitech-proxy-swarm
          - demo-multitech-proxy
      monitoring-network:
        aliases:
          - demo-multitech-proxy-swarm
          - demo-multitech-proxy

networks:
  demo-multitech-network:
    external: true
  monitoring-network:
    external: true
