version: "3"

services:
  server:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    volumes:
      - ${VOLUMES_BASE_DIR}/vault:/vault/file:/vault/file
    networks:
      ci-cd-network:
        aliases:
          - vault
    environment:
      - "VAULT_ADDR=http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK

networks:
  ci-cd-network:
    external: true
