version: "3"

services:
  server:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    ports:
      - 80:80
    networks:
      proxy-nginx-network:
        aliases:
          - proxy-nginx

networks:
  proxy-nginx-network:
    external: true
